num_steps: 250000  # It equals to 200M frames.
batch_size: 32
N: 64
N_dash: 64
K: 32
num_cosines: 64
kappa: 1.0
lr: 5.e-4
memory_size: 20000
gamma: 0.95
multi_step: 1
update_interval: 1
target_update_interval: 1
start_steps: 2000
epsilon_train: 0.01
epsilon_eval: 0.001
epsilon_decay_steps: 6000  # It equals to 1M frames.
double_q_learning: False
dueling_net: False
noisy_net: False
use_per: False
log_interval: 100
eval_interval: 10000
num_eval_steps: 500  # It equals to 500k frames.
max_episode_steps: 500
grad_cliping:
